# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterWindow(object):
    def setupUi(self, FilterWindow):
        FilterWindow.setObjectName("FilterWindow")
        FilterWindow.resize(400, 411)
        self.seall_bttn = QtWidgets.QPushButton(FilterWindow)
        self.seall_bttn.setGeometry(QtCore.QRect(160, 320, 75, 23))
        self.seall_bttn.setObjectName("seall_bttn")
        self.deall_bttn = QtWidgets.QPushButton(FilterWindow)
        self.deall_bttn.setGeometry(QtCore.QRect(160, 350, 75, 23))
        self.deall_bttn.setObjectName("deall_bttn")
        self.fil_data = QtWidgets.QListView(FilterWindow)
        self.fil_data.setGeometry(QtCore.QRect(20, 21, 361, 291))
        self.fil_data.setObjectName("fil_data")
        self.confirm_bttn = QtWidgets.QPushButton(FilterWindow)
        self.confirm_bttn.setGeometry(QtCore.QRect(160, 380, 75, 23))
        self.confirm_bttn.setObjectName("confirm_bttn")

        self.retranslateUi(FilterWindow)
        QtCore.QMetaObject.connectSlotsByName(FilterWindow)

    def retranslateUi(self, FilterWindow):
        _translate = QtCore.QCoreApplication.translate
        FilterWindow.setWindowTitle(_translate("FilterWindow", "FilterWindow"))
        self.seall_bttn.setText(_translate("FilterWindow", "Select All"))
        self.deall_bttn.setText(_translate("FilterWindow", "Deselect All"))
        self.confirm_bttn.setText(_translate("FilterWindow", "Confirm"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     FilterWindow = QtWidgets.QWidget()
#     ui = Ui_FilterWindow()
#     ui.setupUi(FilterWindow)
#     FilterWindow.show()
#     sys.exit(app.exec_())
